name: build-desktop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      ############ Set Up ############

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: install webkit2gtk (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      ############ Build ############

      - name: Build (non-Windows)
        if: matrix.platform != 'windows-latest'
        run: |
          cd packages/desktop
          go build -o ../../emojazz

      - name: Build (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          cd packages\\desktop
          go build --tags no_fallback -ldflags="-H windowsgui" -o ..\\..\\emojazz-no_fallback.exe
          go build -ldflags="-H windowsgui" -o ..\\..\\emojazz.exe

      ############ Packaging (Linux) ############

      - name: Packaging (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          mkdir dist
          mkdir dist/img
          mv emojazz dist/emojazz
          mv packages/desktop/config.yaml packages/nodejs/assets/*.yaml dist/
          mv packages/desktop/public dist/public
          cd dist
          tar -czf ../emojazz-linux.tar.gz *
      - name: Upload binaries to release (Linux)
        if: matrix.platform == 'ubuntu-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: emojazz-linux.tar.gz
          tag: release-${{ github.ref }}
          overwrite: true
          body: Executable for Linux

      ############ Packaging (macOS) ############

      - name: Packaging (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          mkdir dist
          mkdir dist/img
          mv emojazz dist/emojazz.app
          mv packages/desktop/config.yaml packages/nodejs/assets/*.yaml dist/
          mv packages/desktop/public dist/public
          cd dist
          zip -r ../emojazz-macos.zip *
      - name: Upload binaries to release (macOS)
        if: matrix.platform == 'macos-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: emojazz-macos.zip
          tag: release-${{ github.ref }}
          overwrite: true
          body: Executable for macOS

      ############ Packaging (Windows) ############

      - name: Packaging (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          mkdir dist-no_fallback
          mkdir dist-no_fallback\\img
          cp emojazz-no_fallback.exe dist-no_fallback\\emojazz.exe
          cp packages\\desktop\\config.yaml dist-no_fallback
          cp packages\\nodejs\\assets\\*.yaml dist-no_fallback
          cp -r packages\\desktop\\public dist-no_fallback\\public
          cd dist-no_fallback
          tar -cf ..\\emojazz-windows-no_fallback.tar *
          cd -

          mkdir dist
          mkdir dist\\img
          cp emojazz.exe dist\\emojazz.exe
          curl https://raw.githubusercontent.com/webview/webview/master/dll/x64/WebView2Loader.dll --output dist\\WebView2Loader.dll
          curl https://raw.githubusercontent.com/webview/webview/master/dll/x64/webview.dll --output dist\\webview.dll
          cp packages\\desktop\\config.yaml dist
          cp packages\\nodejs\\assets\\*.yaml dist
          cp -r packages\\desktop\\public dist\\public
          cd dist
          tar -cf ..\\emojazz-windows.tar *
      - name: Upload binaries to release (Windows no_fallback)
        if: matrix.platform == 'windows-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: emojazz-windows-no_fallback.tar
          tag: release-${{ github.ref }}
          overwrite: true
          body: Executable for Windows
      - name: Upload binaries to release (Windows default)
        if: matrix.platform == 'windows-latest'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: emojazz-windows.tar
          tag: release-${{ github.ref }}
          overwrite: true
          body: Executable for Windows
